'use strict';

// tests for aggregate
// Generated by serverless-mocha-plugin

const mod = require('../aggregate/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

describe('aggregate', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () =>
    wrapped.run({}).then((response) => {
      // console.log(response);
      response.forEach((d) => {
        console.log(d);
      });

      expect(response).to.not.be.empty;
    }));
});
