'use strict';

// tests for convert
// Generated by serverless-mocha-plugin

const mod = require('../convert/index.js');
const mochaPlugin = require('serverless-mocha-plugin');

const fs = require('fs');

const lambdaWrapper = mochaPlugin.lambdaWrapper;
const expect = mochaPlugin.chai.expect;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'handler' });

const event = require('./s3-event.json');

describe('convert', () => {
  before((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda
    done();
  });

  it('implement tests here', () =>
    wrapped.run(event).then((response) => {
      fs.writeFileSync('temp.mp3', response.AudioStream);
      expect(response).to.not.be.empty;
    }));
});
